import html2canvas from "html2canvas"
import jsPDF from "jspdf"

interface Roadmap {
  title: string
  description: string
  nodes: Array<{
    id: string
    data: {
      label: string
      description: string
      difficulty: string
      resources: Array<{
        title: string
        url: string
        type: string
      }>
    }
  }>
  edges: Array<{
    id: string
    source: string
    target: string
  }>
}

export async function exportToPDF(roadmap: Roadmap) {
  try {
    // Create a temporary div with the roadmap content
    const element = document.createElement("div")
    element.style.width = "800px"
    element.style.padding = "20px"
    element.style.backgroundColor = "white"
    element.style.color = "black"

    element.innerHTML = `
      <h1 style="font-size: 24px; margin-bottom: 10px;">${roadmap.title}</h1>
      <p style="margin-bottom: 20px; color: #666;">${roadmap.description}</p>
      
      <h2 style="font-size: 18px; margin-bottom: 15px;">Learning Path</h2>
      ${roadmap.nodes
        .map(
          (node, index) => `
        <div style="margin-bottom: 15px; padding: 10px; border: 1px solid #ddd; border-radius: 8px;">
          <h3 style="margin: 0 0 5px 0; font-size: 16px;">${index + 1}. ${node.data.label}</h3>
          <p style="margin: 0 0 10px 0; font-size: 14px; color: #666;">${node.data.description}</p>
          <div style="font-size: 12px;">
            <strong>Difficulty:</strong> ${node.data.difficulty}
          </div>
          <div style="margin-top: 8px;">
            <strong style="font-size: 12px;">Resources:</strong>
            <ul style="margin: 5px 0 0 20px; font-size: 12px;">
              ${node.data.resources
                .map(
                  (resource) => `
                <li><a href="${resource.url}" style="color: #0066cc;">${resource.title}</a> (${resource.type})</li>
              `,
                )
                .join("")}
            </ul>
          </div>
        </div>
      `,
        )
        .join("")}
    `

    document.body.appendChild(element)

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
    })

    document.body.removeChild(element)

    const imgData = canvas.toDataURL("image/png")
    const pdf = new jsPDF("p", "mm", "a4")

    const imgWidth = 210
    const pageHeight = 295
    const imgHeight = (canvas.height * imgWidth) / canvas.width
    let heightLeft = imgHeight

    let position = 0

    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight)
    heightLeft -= pageHeight

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight
      pdf.addPage()
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight)
      heightLeft -= pageHeight
    }

    pdf.save(`${roadmap.title.toLowerCase().replace(/\s+/g, "-")}-roadmap.pdf`)
  } catch (error) {
    console.error("PDF export failed:", error)
    throw error
  }
}

export function exportToMarkdown(roadmap: Roadmap) {
  const markdown = `# ${roadmap.title}

${roadmap.description}

## Learning Path

${roadmap.nodes
  .map(
    (node, index) => `
### ${index + 1}. ${node.data.label}

**Difficulty:** ${node.data.difficulty}

${node.data.description}

**Resources:**
${node.data.resources.map((resource) => `- [${resource.title}](${resource.url}) (${resource.type})`).join("\n")}

`,
  )
  .join("")}

---
*Generated by AI Roadmaps Platform*
`

  const blob = new Blob([markdown], { type: "text/markdown" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${roadmap.title.toLowerCase().replace(/\s+/g, "-")}-roadmap.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function exportToJSON(roadmap: Roadmap) {
  const jsonData = JSON.stringify(roadmap, null, 2)
  const blob = new Blob([jsonData], { type: "application/json" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${roadmap.title.toLowerCase().replace(/\s+/g, "-")}-roadmap.json`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
